apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    secretRef: redis-host
  - name: redisPassword
    secretRef: redis-password
  - name: enableTLS
    value: "true"
scopes:
- productservice
- orderservice
